oauthClient:
  redirectUris:
    - http://sulmo.link/login/callback
  applicationType: browser
trustedOrigins:
  - http://sulmo.link

directions: |+2
  Okta configuration written to: .okta.env

  Build this example using NPM:

      npm install

  And run with:

      npm start
