name: "[Dispatch] Dev build"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      TIME: ${{ steps.get_date.outputs.TIME }}
    steps:
      - name: log
        run: |
          echo "BRANCH: ${{ github.event.inputs.branch }}"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          submodules: recursive
